### PR TITLE
Use Cython to speedup unidecoding

### PR DESCRIPTION
**Pull request by dukebody**
The current code loops over all the chars in the given string to "unidecode", which is slow in Python. I propose compiling the code with minor changes using Cython.
## My tests under Python 3.4

Old code:

```
python -m timeit -s 'from unidecode import unidecode' 'unidecode("Hello world! ñ ŀ ¢")'
100000 loops, best of 3: 4.09 usec per loop
```

New Cython code:

```
python -m timeit -s 'from unidecode import unidecode' 'unidecode("Hello world! ñ ŀ ¢")'
1000000 loops, best of 3: 0.934 usec per loop
```

So using Cython represents an improvement of approximately 4x in speed.

This pull request includes a tox.ini config file to test the install with Python 2.7 and 3.4, with or without Cython installed. 

The only extra required here would be a C compiler, which might be an issue in Windows. We can try to find a way to use the fast version when there is a C compiler available, and the slow one when there isn't any.

### CODE REVIEW

**Comment by iki** [comment]
Thanks @dukebody. Please give me a few weeks to find some time and setup how we work together with @avian2 who runs the project and maintains the official repo outside github.

**Comment by avian2** [comment]
In my experience, compiling C modules for Python is usually a pain on many systems. As you mention, Windows might be an issue, and also this change would make Unidecode unusable on any Python that is not CPython (PyPy, Jython, ...) I would say this change complicates things for a relatively minor gain. For most people I believe Unidecode performance is simply not an issue.

There are also more compatible ways to increase performance of Unidecode. One idea is to make an Unidecode error handling function with `codecs.register_error` [1] and then use `unicode.encode("ASCII", errors="unidecode").decode("ASCII")`. A while back somebody reported that gives ~100x performance increase in cases where text is mostly ASCII with occasional non-ASCII character. However so far, nobody has contributed that code.

[1] https://docs.python.org/2/library/codecs.html#codecs.register_error

**Comment by dukebody** [comment]
Hi Tomaž.

Would it be ok to create a package version that uses the C-compiled version
if a C compiler is available, and the basic non-compiled version if not?

I'll take a look at the codecs error registration approach, since I use
this code in production and ~100x performance improvement sounds like
something I'd like to have. :)

Regards,

2015-10-19 11:44 GMT+02:00 Tomaž Šolc notifications@github.com:

**Comment by dukebody** [comment]
I mean something like http://nedbatchelder.com/blog/201212/skipping_c_extensions.html

**Comment by dukebody** [comment]
I've created https://github.com/dukebody/unidecode/tree/codecs, but it is slower than the current version when dealing with non-ASCII:

```
python -m timeit -s 'from unidecode import unidecode' 'unidecode("Hello world! ñ ŀ ¢")'
100000 loops, best of 3: 8.21 usec per loop
```

It's however faster when dealing with ASCII-only strings.

Error-handler version:

```
python -m timeit -s 'from unidecode import unidecode' 'unidecode("Hello world!")'
1000000 loops, best of 3: 0.69 usec per loop
```

Current master version:

```
python -m timeit -s 'from unidecode import unidecode' 'unidecode("Hello world!")'
100000 loops, best of 3: 2.2 usec per loop
```

However I don't know if I'm doing something wrong here, but it's far from 100x speedup...

**Comment by avian2** [comment]
@dukebody Sorry for not getting back to you for so long.

Yes, having an automatic fallback to pure Python code would be the right way. The article you linked refers to "simplejson". I like how it's completely transparent to the user, both at install time and when using it (it tries to import from `simplejson._speedups` and falls back if that fails).

Can you please base your work on https://github.com/avian2/unidecode? This is the version that is released on PyPi.

By the way, `tox` fails for me on your branch (Debian Wheezy, tox 2.1.1)

```
$ tox
py27-cython installed: async==0.6.1,authres==0.402,BeautifulSoup==3.2.1,boto==2.3.0,bpython==0.11,catkin==0.6.11,chardet==2.0.1,Cheetah==2.4.4,CherryPy==3.2.2,configobj==4.7.2,cssutils==0.9.10b1,Cython==0.23.4,datadiff==1.1.4,dblatex==0.3.4.post2,devscripts===2.12.6-deb7u2,dnspython==1.10.0,duplicity==0.6.23,eagle-automation==0.0.1,fcd-scanner==0.1,feedparser==5.1.2,gbp===0.6.22-bpo70-1,GDAL==1.9.0,gdata==2.0.17,gdmodule==0.56,gitdb==0.5.4,GitPython==0.3.2rc1,gps-tools==0.1,gr==0.5.2,httplib2==0.7.4,icalendar==3.5,iotop==0.4.4,Jinja2==2.6,jsonmerge==0.0.1,louis==2.4.1,lxml==2.3.2,lzw==0.1.11,Magic-file-extensions==0.2,Mako==0.7.0,Markdown==2.1.1,MarkupSafe==0.15,mechanize==0.2.5,mercurial==2.2.2,netifaces==0.8,numpy==1.8.2,paramiko==1.7.7.1,pep8==1.2,pexpect==2.4,ply==3.4,pycrypto==2.6,pydns==2.3.6,pygame===1.9.1release,PyGithub==1.23.0,Pygments==1.5,pygobject==3.10.1,pykalman==0.9.5,PyOpenGL==3.0.1,pyparsing==1.5.6,pyserial==2.5,pyspf==2.0.7,Pyste==0.9.10,python-apt==0.8.8.2,python-dateutil==1.5,python-debian==0.1.21,python-vxi11==0.5,pytz==2012rc0,pyudev==0.13,PyYAML==3.10,pyzmq==14.4.0,reportlab==2.5,repoze.lru==0.5,Routes==1.13,scipy==0.10.1,simplejson==2.5.2,smmap==0.8.2,sqlitedict==1.0.9,Unidecode==0.4.10,uTidylib==0.2,WebOb==1.1.1,wheel==0.24.0,wxPython-common==2.8.12.1
py27-cython runtests: PYTHONHASHSEED='746654432'
py27-cython runtests: commands[0] | python setup.py test
running test
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    ext_modules = extensions,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 41, in run
    UNITTESTS ) )
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/avian/syn/dev/unidecode/unidecode/tests/__init__.py", line 6, in <module>
    from .basic_2 import *
  File "/home/avian/syn/dev/unidecode/unidecode/tests/basic_2.py", line 4, in <module>
    from unidecode import unidecode
  File "/home/avian/syn/dev/unidecode/unidecode/unidecode/__init__.py", line 1, in <module>
    from main import unidecode
ImportError: No module named main
ERROR: InvocationError: '/home/avian/syn/dev/unidecode/unidecode/.tox/py27-cython/bin/python setup.py test'
```

Regarding the codecs approach, I've made a mistake. Sorry. I've searched back through my mail and this was the exact code that was suggested for "a large number of short strings with most of them actually ASCII". Note that this works in principle, but takes `str` and returns either `str` or `unicode`, while Unidecode is vice-versa regarding types (which is why I didn't accept this patch).

```
def unidecode_fast(s):
  if type(s) == str:
    return s
  try:
    return s.decode("ascii")
  except UnicodeEncodeError:
    return unidecode(s)
```

**Comment by dukebody** [comment]
Hi Tomaž! I'm now thinking that the Cython speed-up improvement might not be worth the effort if we already implement some of the mostly-ascii speed-ups we talked about. What do you think?

**Comment by avian2** [comment]
I agree.

**Comment by dukebody** [comment]
Ok, closing it then. :)

**Pull request closed without merging**
